### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by cosmina98** [fabriziocosta/EDeN#140]
I was working on Collab and I realised that these lines from eden/ml/ml.py need to be updated/deleted , otherwise we get error when importing after installing via pip

from sklearn.grid_search import RandomizedSearchCV
(from sklearn.model_selection import RandomizedSearchCV)
from sklearn import cross_validation
(from sklearn.model_selection import cross_validate)

**Comment by fabriziocosta** [comment]
OK
