### ISSUE TITLE
add dask integration

### ISSUE THREAD

**Issue by bgruening** [fabriziocosta/EDeN#47]
```
Dask enables parallel computing through task scheduling and blocked algorithms. 
This allows developers to write complex parallel algorithms and execute them
in parallel either on a modern multi-core machine or on a distributed cluster.
```

http://dask.pydata.org/en/latest/index.html

**Comment by fabriziocosta** [comment]
it is generally not worth the while to use Dask. 
in fact the vectorization is so low level and efficient that the parallelization should happen at higher abstraction  level.
