### ISSUE TITLE
nodes_iter() is not available in networkx 2.0

### ISSUE THREAD

**Issue by zaidurrehman** [fabriziocosta/EDeN#53]
EDeN uses G.nodes_iter() and G.edges_iter() for a graph G. These methods are removed from the latest version 2.0 of networkx. Using only G.nodes() will do the same job now as that of G.nodes_iter().

for reference: https://networkx.readthedocs.org/en/latest/reference/release_2.0.html

**Comment by bgruening** [comment]
Thanks for the report. We have a fix in #54. But you should be able to install the latest stable version of networkx (1.10).
